name: publish-package-on-release

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt
      -
        name: Get Current Tag
        uses: olegtarasov/get-tag@v2.1
        id: currentTag
      -
        name: Update version info
        run: |
          echo "${{ steps.currentTag.outputs.tag }}" > VERSION.txt
          sed 's/.*VERSION = ".*/VERSION = "${{ steps.currentTag.outputs.tag }}"/g' pwnbox/__main__.py
          sed 's/.*VERSION = ".*/VERSION = "${{ steps.currentTag.outputs.tag }}"/g' setup.py
      -
        name: Build python package
        run: |
          python setup.py sdist bdist_wheel
      -
        name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      -
        name: Push the updated version info
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          author_name: Github Action
          author_email: action@github.com
          message: '[GitHub Action] Update version info'
          branch: main
          push: true
      -
        name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: 'main'